### ISSUE TITLE
Voting process as a decision tree

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/interoperability#185]
We need to define and implement a system that allows for generating a voting process with different flows based on the voter's selected option. For example, if a voter selects "Option X," they should then be presented with another question defined in Process Y.

This use case will be generated by script, not through the UI. If possible, we will use metadata to store the information that the frontend will use to properly render the flow.

**Proposed Flow:**
    - The frontend will read the proposed metadata structure.
    - The frontend will display the initial question/questions.
    - After the voter submits their vote, the frontend will render another question based on the previously defined process.

**Proposed Structure for Metadata:**
    - Define the initial question and available options.
    - For each option, define the subsequent question or action (or let them empty for "no action").
    - Use metadata to store these relationships and processes.
    
 **Tasks:**
 - Define and agree on the data structure and where to store it
 - Update the UI to read the specified field and, if the conditions are meet, render the next question to present to the voter
 - Update the results on the "primary" voting process to show all the sub-processes questions/results.
 - Test the flow and make sure a logged user can vote in all the different questions.

**Comment by jpaulet** [comment]
1st proposed structure:

```
"multiprocess" { 

	"processes": [ 
			1: "0x12345", 
			2: "0x56789", 
			3: "0xabcde" 
		      ], 
	"start": 1, 
	"dependencies": [ 
			   2: "1:1 or 1:3", 
			   3: "1:1 and 2:2" 
			] 
}

```

**Comment by elboletaire** [comment]
There's a first version that takes basic conditions into consideration. The creation of the processes is managed by the new [`chained`](https://github.com/vocdoni/projects/tree/main/packages/chained) package in the projects repo, and the rendering and logic of these is currently only handled by the voting-page (most changes were done in this commit https://github.com/vocdoni/ui-voting-page/commit/e3a6bc5f66ba6d34642548309eedd334737c637a)

The current behavior is only taking into consideration the very first question, and can't handle multiple conditions. Adding multiple clauses should be assessed thoroughly, since it can worse the user and developer experience.``

**Comment by elboletaire** [comment]
Closing as done for now. Consider reopening if there's anything else that should be tracked.

Not adding it to ui-scaffold since we haven't used it at all yet (meaning there are equal chances of removing it or implementing it into ui-scaffold).
