### ISSUE TITLE
New API Error handling

### ISSUE THREAD

**Issue by p4u** [vocdoni/interoperability#19]
@altergui please explain the changes and reference the errors file so @selankon and @marcvelmer can start using the same approach.

**Comment by altergui** [comment]
it's not yet finished but i'll outline the general idea so far:

in https://github.com/vocdoni/vocdoni-node/blob/d078639c718ff9683d95be0b997bb2802d2589b4/api/errors.go
you'll find all the errors used in the api package.

each error has a code (for example ErrDstAddressMalformed = 4001) and a string associated (the comment at the end of the line, "destination address malformed")

the string might change but we commit to keep the error code stable, so that the API clients can match the code

**Comment by altergui** [comment]
some examples:

```
> GET /v2/accounts/deadbeef HTTP/1.1
> Host: 127.0.0.1:9090
> User-Agent: curl/7.74.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 400 Bad Request
< Content-Length: 42
< Content-Type: application/json
< Vary: Origin
< Date: Mon, 27 Feb 2023 19:16:00 GMT
< 
{"error":"address malformed","code":4000}
```



```

> GET /v2/elections/deadbeef HTTP/1.1
> Host: 127.0.0.1:9090
> User-Agent: curl/7.74.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 404 Not Found
< Content-Length: 43
< Content-Type: application/json
< Vary: Origin
< Date: Mon, 27 Feb 2023 19:17:44 GMT
< 
{"error":"election not found","code":4045}
```

and the exceptional 204:

```
> GET /v2/chain/transactions/reference/FFfFfFffFFfffFFfFFfFFFFFffFFFffffFdeadbeef HTTP/1.1
> Host: 127.0.0.1:9090
> User-Agent: curl/7.74.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 204 No Content
< Content-Type: application/json
< Vary: Origin
< Date: Mon, 27 Feb 2023 19:15:01 GMT
< 
```


not ALL errors have a specific code assigned (too many coming from too many places), so in case an unexpected error comes up the stack, it's exposed in plaintext with 500 Internal Server Error. Here's an example:
```
> GET /v2/chain/transactions/reference/reallyWrong HTTP/1.1
> Host: 127.0.0.1:9090
> User-Agent: curl/7.74.0
> Accept: */*
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< Content-Length: 39
< Content-Type: application/json
< Vary: Origin
< Date: Mon, 27 Feb 2023 19:22:53 GMT
< 
encoding/hex: invalid byte: U+0072 'r'
```

What do you think so far?

**Comment by altergui** [comment]
now that i have a better overview, i'm digging deeper into how we are reporting errors, and comparing with other implementations (Etherscan and Infura, out of the top of my head)

etherscan, as far as i understood, always reports 200 OK, so errors, if any, are reported in the JSON body. they do reply with 404 on https://api.etherscan.io/totallyWrong, but AFAICT any call to /api gives 200 OK, and also there's no documentation regarding HTTP Status codes

infura does document their HTTP Status codes very nicely
https://docs.infura.io/infura/networks/ipfs/http-api-methods#http-status-codes
and these two lines caught my eye

> 404 - RPC endpoint doesn't exist

> A 405 error may mean that you are using the wrong HTTP method (i.e. GET instead of POST), or that you are not allowed to call that method (i.e. due to CORS restrictions when making a request from a browser).

since it differs from what we currently do (we return 405 for nonexistent endpoints)

and i hate to be bearer of bad news, but the way we're using `405 Method Not Allowed` is... wrong.
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405
> The HyperText Transfer Protocol (HTTP) 405 Method Not Allowed response status code indicates that the server knows the request method, but the target resource doesn't support this method.
> 
> The server must generate an Allow header field in a 405 status code response. The field must contain a list of methods that the target resource currently supports.

we're not even following the "MUST generate an Allow header"
```
$ curl 'http://127.0.0.1:9090/v2/nonexistent'  -i
HTTP/1.1 405 Method Not Allowed
Vary: Origin
Date: Tue, 28 Feb 2023 13:08:12 GMT
Content-Length: 0
```

i'm going to propose a PR to change this (return 404), i hope it's no big deal

**Comment by selankon** [comment]
FTR: 

On the past weekly we decided to don't document each endpoint error responses because is not prioritary. 

Instead, point the error file from somewhere on the docs.

**Comment by selankon** [comment]
After today interop meeting we decided to see where and how integrate this on the API docs, at least on a general way, because is useful for us or for a developer to have at least one reference to the error messages.

**Comment by selankon** [comment]
Talking with Aulet, for the moment, we are going to reference the error file on to the api introduction page.
