### ISSUE TITLE
Add "results per page" and "total" results fields to pagination responses

### ISSUE THREAD

**Issue by elboletaire** [vocdoni/interoperability#26]
Right now, when trying to get paginated results from the API, we need to make two calls:
- A first one to `page/0` to retrieve the very first page
- A second one to the `/count` endpoint to retrieve the total number of results

This is a bit counter-productive for both of us, since most front-end implementations need to know the total number of results, meaning most front-end implementations will need to make this two calls always when paginating results.

There's also another field that makes a lot of sense to be returned alongside the results and the total ones: one with the total items per page. Obviously we could calculate this every time from the implementation based on the results received in the very first page and the total number of results, but adds technical debt in every implementation, plus it can fail in some specific scenarios.

This is a bit related to #8, since most of those endpoints are pagination endpoints, and actually there's a suggestion for a `totalResults` field already (but my request is to add these fields to every paginated endpoint).

**Comment by p4u** [comment]
Ok, but we need more concretion. Can you propose what new fields or endpoints would you add to the API?

**Comment by jpaulet** [comment]
Waiting for @mvdan counter with SQLite

**Comment by mvdan** [comment]
Apologies for the slowness, I was struggling with this for a few days. I was wrong about the total being cheap for SQL; with queries like `SearchProcesse`s, used by API endpoints like `/elections/page/N`, we would have to fetch **every matching process** to get the total count even if the query said `from = 5, max = 10`.

Imagine a large case with 1,000 processes; with a page size of 10, instead of doing 100 queries going over 10 processes each, the new method (also including the total) would result in 100 queries going over all 1,000 processes. The total cost would skyrocket by 100x. I think this slowness would be a big problem sooner than later. The indexer exists to be able to query over many thousands of values, after all.

I see two possible approaches to avoid this:

1) Do not rely on accurate total counts in the UI. The UI could simply show "previous page" and "next page", for example.

2) Request the entire list (without pagination) from the backend API when the UI needs to show the total number of pages. If there are 1,000 processes, the new method would be just as costly no matter what page size I use in a query, so asking for the first 10 processes is just as expensive as asking for the first 100 or all 1,000. So, the UI could ask for all 1,000, keep them somewhere, and allow moving between pages without more API calls.

Another data point: with SQL, the "proper" way to do pagination is not with OFFSET and LIMIT, like we currently do. That has significant limitations, like the pages "jumping" if INSERTs happen while the user is browsing. Cursors are usually the solution, as they let you start a query, and advance row by row to get more values without being affected by outside factors. It is also efficient - but for that reason, it doesn't tell you the total number. It only tells you whether more values are available, like an iterator.
