### ISSUE TITLE
Vote Overwrites Overflow bug

### ISSUE THREAD

**Issue by jpaulet** [vocdoni/interoperability#37]
If you set the "voteOverwrite" value to -1, it overflows and allows "infinite" overwrites. 

Always check if the value is <0 and return an error (either from the chain and the SDK).

**Comment by p4u** [comment]
The description of the issue is not correct.

The maxVoteOverwrite field is a uint32 which is parsed from a Protobuf model https://github.com/vocdoni/dvote-protobuf/blob/master/src/vochain/vochain.proto#L407

Depending on the protobuf/language behavior implementation, if -1 i set to a uint32 it would be coded as `MaxUint32-1`.
Thus is javascript allows to set a -1 on the maxVoteOverwrite field before serializing the transaction to protobuf, the overwrite maximum should be equal to `2^32-1`. 

This is correct. The thing is that this election will be very expensive and probably the user does not have enough credit for paying it.

**Comment by p4u** [comment]
However we might consider adding a maximum vote overwrite to avoid this kind of weird behavior.

**Comment by jpaulet** [comment]
Ok. Closing it, but I think that the vote overwrite limit should be more limited, like from 0 to 100 (bc I cannot find a uses case that needs more than 10 votes overwrites per user, and 100 it's a x10 this limit). 

But as you said, the election price will be very high and it's their choice.
