### ISSUE TITLE
Choose an OpenAPI generator library 

### ISSUE THREAD

**Issue by emmdim** [vocdoni/interoperability#62]
Choose an OpenAPI generator library evaluating:
   - Information included : URL, URL variable, Errors
   - Presentation of information in relation with how it is presented in the Documentation

**Comment by selankon** [comment]
Following @altergui instructions, I tried swago (from vocdoni node repo):

```bash
cd api
go get github.com/swaggo/swag/cmd/swag
go run github.com/swaggo/swag/cmd/swag init --parseDependency --parseDepth 1 --parseInternal -g api.go
```

This generate a Yaml swagger specification, I found the following problems:

* It don't pass the swagger schema validation because it misses some needed attributes. Paste de swagger [here](https://editor.swagger.io/) to see errors. For example:

```yaml

  /accounts:
    post:
      description: Set account information
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/components/schemas/blah'
      summary: Set account
```

Should be:

```
/accounts:
    post:
      description: Set account information
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/blah'
      summary: Set account
```

This causes that the generated docusaurus pages are broken. 

* We should add `tags` and `info` to be more complete. This is added on the commented code. 
* Path parameters are missing causing errors (we should define the parameters on the comments for paths like `/censuses/{censusID}/export` )

**Comment by altergui** [comment]
> [](https://github.com/swaggo/swag/issues/548)
> 
> Anyway, please, could you paste here the yaml file generated? 
https://raw.githubusercontent.com/vocdoni/vocdoni-node/3b4f3866e416b5730d32e11c73666665522344e6/api/docs/swagger.yaml

**Comment by selankon** [comment]
Hi @chilcano 

We are using a docusaurus package to generate the docs: https://github.com/PaloAltoNetworks/docusaurus-openapi-docs (is not a docusaurus feature). 

Reading the README.md should work with Swagger 2.0 and OpenAPI 3.0. And in fact, I was using the generated Swagger 2.0 schema with the OpenAPI 3.0 annotation, which is an error. 

After running it again with the correct tag I saw this message when generating the docs: `[ReDoc Compatibility mode]: Converting OpenAPI 2.0 to OpenAPI 3.0`, so it seems to perform some conversion underneath. 

So, after correcting the tag, everything worked as expected and the generated pages seems working now! 

BTW: https://github.com/swaggo/swag/issues/548#issuecomment-1498284724 swaggo has beta suport for OpenAPI 3.0 on April 6 :)

**Comment by selankon** [comment]
FTR [codeExampleFiles](https://redocly.com/docs/api-reference-docs/specification-extensions/x-code-samples/) option is used to give code samples like curl so is not needed for us
