### ISSUE TITLE
Throw API error when vote is invalid

### ISSUE THREAD

**Issue by selankon** [vocdoni/interoperability#69]
Actually, when you try to perform a vote above the credits limit on a quadratic voting election, the vocdoni node shows a error on the log:

```
 ERR indexer/indexer.go:420 > vote cannot be added to results error="max total cost overflow: 10"
```

But this error is not thrown outside the vocdoni node, so the SDK user cannot know that this vote is not performed. 

To test it the quadratic vote example of the sdk can be used.

Probably this is not the only vote type that is not throwing an error when the vote is invalid. Generally, submitting a wrong vote is accepted by the API but the vote is not performed.

- [ ] Vocdoni node fix
- [ ] Update docs

**Comment by p4u** [comment]
The "compute votes in real time" feature of the indexer, isn't always enabled by the Gateway admin, and its applicability is restricted to plaintext elections. This makes the prospect of integrating it into the API inconsistent at best.

Moreover, the verification occurs during Block production, not when the transaction is sent. Under normal circumstances, this can result in a delay of up to 10 seconds before the warning appears, and during busy network periods, this could stretch to several minutes.

Considering these factors, relying on this "weak check" on the SDK/Client side might not be the best approach. I believe we should empower users with all the necessary tools to verify a vote's validity before sending it, rather than depending on Vochain for this verification.

I'm open to discussing specific scenarios where checking the vote's validity might prove challenging. Please feel free to share such cases, and we can further explore potential solutions.

**Comment by selankon** [comment]
This could be closed because is not an error.
